### ISSUE TITLE
Which LCD ?

### ISSUE THREAD

**Issue by spilz87** [shufps/diy-projector-clock#1]
Hello, 
Very nice project, I was thinking about it for years but I didn’t find how to find the lcd. 
Where did you buy the lcd ?
What’s it with backlight led that you removed ?
Thanks for your project
Regards

**Comment by shufps** [comment]
Hi, sorry for answering so late ... In the repo there is a directory called "BOM" (bill of material) and in the text-file "others" there is the LCD which works:

LCD:
(search on ebay for LCD 64x32) e.g.
GLS Neu LCD-VATN 64x32 3V ST7567A I2C 15x12x2mm [LCD-AG-064032V-VIW W/KKK-E6]

**Comment by shufps** [comment]
Ah forgot to answer the other question - you simply can remove without much force the backlight from the LCD :)

**Comment by spilz87** [comment]
Thanks for your replies :)
I didn’t see the BOM folder ...

I found your lcd on eBay for about 15€ shipping included
Is there a difference with another classic RGB lcd ? (Except the size maybe)
I found this lcd on AliExpress, for about 2.5€ :

https://www.google.fr/amp/s/m.aliexpress.com/item/32859445140.html#ampf=undefined

If I use it as “black/white”, is there a way it will work as yours (optically I mean, not necessary the driver) ?
(After removing pcb and background led)
Thanks for your help

**Comment by shufps** [comment]
No, OLEDs can't be used for projectors in general.

Buy this:
https://www.ebay.de/itm/GLS-Neu-LCD-VATN-64x32-3V-ST7567A-I2C-15x12x2mm-LCD-AG-064032V-VIW-W-KKK-E6/391734506852?hash=item5b35323564:g:JzYAAOSwcOdZ5JXN:rk:1:pf:0

**Comment by spilz87** [comment]
Actualy, the one I found was NOT oled according to the description.

Thanks for the link, I will buy it :)

You explained that it was a negative monocolor LCD. I wondered if it was necessary or if a conventional RGB LCD does the same job.

your project made me want to build mine :)

**Comment by shufps** [comment]
Ah sorry, you are right ... Just read "OLED" at the end of the title and missed the "not" before xD
You can try, but you will have to change everything ... This would be a lot of work and would be very time consuming. If you do, I would be interested in your results :)

But I don't know how good the contrast will be ... perhaps black background is milky then. This small little LCD seems to have been build for projecting applications - but of course we don't know for real.

**Comment by spilz87** [comment]
The contrast could be the issue with this RGB lcd, that why I’m thinking using it only in white/black, hopping it will be enough ...

Your small lcd seems to be design to feet in key :
Q5-100-STARTER-KIT 64x32 Spi Lcd Switch & Breakout Board https://rover.ebay.com/rover/0/0/0?mpre=https%3A%2F%2Fwww.ebay.com%2Fulk%2Fitm%2F132276707938

The electronic hardware shouldn’t be a problem, I’m thinking using an ESP32 to control display, get time through internet and maybe to project small icon of weather :)

My real issue in my project was what you solved : the optical hardware

I will let you know when I will receive the components and share with you my knowledge and my project if you want 

I will maybe have more questions ^^

**Comment by shufps** [comment]
Niiiiice! Thank you for the link! That could be the reason why this LCD exists :-)

Looking forward hearing about your progress! :-)

**Comment by spilz87** [comment]
Hello,
I’m working a lot on this project and it start to work well. 
Until now I’m using the LCD 160x80 in SPI. 
But I would like to have it brighter so I will test the same LCD as you. 
Can you tel me more about the connection of this LCD : 
Which pin of the LCD did you connect to 3.3v ? (On datasheet there are pins for dc/dc converter and one for 3.0v)
Why did you keep the led pin ? 
Thanks for your help

I don’t know how to send photo of my project

**Comment by shufps** [comment]
Hello,

ah yes, why did I keep the Pin for the backlight - I don't know to be honest ... The back light is removed anyways xD Perhaps to be able to use it for different applications which need backlight.

I connected Pin 8 to 3.3V. You can open the schematic with KiCad.

**Comment by Pilgrim182521** [comment]
Hi guys,
just started looking for LCD glass and found something like this in EU:
https://allegro.pl/oferta/art-lcd-vatn-64x32-3v-st7567a-i2c-15x12x2mm-whiten-6754828746 
for some 3 Euros, shipping  included.
josef

**Comment by trizmark** [comment]
Hey @shufps 

Do you have a recent link to an LCD display? This is an awesome project and I'm finding it hard to locate a suitable LCD.

Thanks,
Zoltan

**Comment by Pilgrim182521** [comment]
https://allegro.pl/oferta/art-lcd-vatn-64x32-3v-st7567a-i2c-15x12x2mm-whiten-6754828746
is still valid...
Josef

**Comment by Pilgrim182521** [comment]
... whoops sorry, it has not been query for me... ;)

**Comment by trizmark** [comment]
> ... whoops sorry, it has not been query for me... ;)

I had a look at that, but due to the current COVID-19 situation that website have stopped delivering to non-Polish addresses... :(

Appreciate the reply anyway!

**Comment by AmbroAnalog** [comment]
The store Allegro.pl now seems to deliver outside Poland again, I received my shipment to Germany today.

How exactly do I get the display transparent to show through with the LED? Do I have to remove the black layer at the back?

**Comment by Cthanatos** [comment]
Any chance you could provide an aliexpress link? I've tried the link above and it's in Polish, and Google's translate page feature isn't great. I've tried searching  the line from the BOM, even parts of the line but I can't seem to find what I'm looking for....

**Comment by jghaanstra** [comment]
Anyone ever found a suitable replacement for the led screen in the project? I tried ordering through the Polish webshop but there is an issue with delivery and I probably lost my money. I have been unsuccesful finding a replacement.

**Comment by spilz87** [comment]
If you are able to change the library you can take any lcd screen. 
I'm using 0.96in tft display 80x160 with arduino based electronics and it works well

**Comment by spilz87** [comment]
€ 1,69  11％ Off | 2022 New 0.96in TFT Display Module IPS Color Screen SPI For LCD 80x160 ST7735 Drive Welded Spliced Link
https://a.aliexpress.com/_vMIfpr

**Comment by trizmark** [comment]
But that's not a negative LCD, right? So how would you use that for projection?

**Comment by spilz87** [comment]
You have to remove the backlight

**Comment by jghaanstra** [comment]
Actually just bought me the black version of [this ](https://nl.aliexpress.com/item/4000370015852.html?gatewayAdapt=glo2nld&spm=a2g0o.9042311.0.0.49714c4dHxym9T) one to try out. It comes without the backlight.

I'll be figuring out the library part myself so I learn something from it. It's my first real ESP32 tinker project.

**Comment by spilz87** [comment]
Thanks for the link, I didn't saw it 

But the density of pixel is not as good, and the issue I didn't solved is a way to have an homogeneous light before the lcd screen

**Comment by jghaanstra** [comment]
> Thanks for the link, I didn't saw it
> 
> But the density of pixel is not as good, and the issue I didn't solved is a way to have an homogeneous light before the lcd screen

I assume you mean the light behind the LCD screen? Did you use some form of condensor to try and get an homogeneous light?

**Comment by spilz87** [comment]
Yes the light behind the lcd screen 

I tried several things but I always have something not homogeneous :( 

What do you use for it ?

**Comment by jghaanstra** [comment]
I just started looking into all this and I have no experience with these kind of projects. But I bought [this ](https://www.aliexpress.com/item/1W-3W-Constant-Current-LED-Driver-Warm-Natural-Cool-White-Blue-Red-Green-Yellow-LED-Chip/32984506965.html?spm=a2g0o.9042311.0.0.49714c4dHxym9T) one as a first attempt. And I thought I just reflective tape or aluminum foil for extra spread.

**Comment by spilz87** [comment]
The link does not work for me

**Comment by zoltan-vonage** [comment]
> You have to remove the backlight

How hard is it to remove the backlight?

**Comment by trizmark** [comment]
> You have to remove the backlight

How hard is it to remove the backlight?

**Comment by jghaanstra** [comment]
> The link does not work for me

Does [this ](https://aliexpress.com/item/32984506965.html) work?

**Comment by spilz87** [comment]
Yes the link works

I already tried this but it's not homogeneous and you saw it on the wall

**Comment by jghaanstra** [comment]
> Yes the link works
> 
> I already tried this but it's not homogeneous and you saw it on the wall

OK. what gave you the best results?

**Comment by spilz87** [comment]
The best I found was a led with this :

€ 0,98 | Cree XPG lens Diameter 23.5mm (Belt holder) 5 degrees LED Lens, glass Condenser lens,
https://a.aliexpress.com/_vl5RYv

But not perfect 

And as the screen is bigger, you see halo on the wall :(

**Comment by catalin7** [comment]
i did my clcocprojector from a laying around clock projector. I hacked the communication to the lcd's driver with a logic analyzer, in a day i had my communication protocol established and for fun actually i have 4 display projectors , i use only 1 , my bestie. Some clocks dont have lcd driver, the lcd is connected tru a plastic conductive ribbon to the lcd. These are not good. 
So my clocks are one from an Accurite, 2 from a Mesqool CR1001 i think, and another one from a LaCrosse not working clock

**Comment by catalin7** [comment]
![Image](https://github.com/user-attachments/assets/16b80025-fd54-4b5c-926f-34d0c6e7238c)

**Comment by spilz87** [comment]
Thanks for sharing 
I worked also on it and I was able to create my own one from classic lcd (no oled) by removing some back parts (not that easy, I broke some 😅)

The most difficult part is to find an homogenized light source.. 

![Image](https://github.com/user-attachments/assets/2b6d6cdf-26cf-4585-95c8-282ed0973e23)
![Image](https://github.com/user-attachments/assets/c4394882-78a0-461d-9550-7d240e3eb77d)
![Image](https://github.com/user-attachments/assets/c2f2a9de-7f15-4f39-8826-6325df35f4a7)

**Comment by spilz87** [comment]
![Image](https://github.com/user-attachments/assets/ad08df72-e8c4-44a5-961b-29225fb7c695)
![Image](https://github.com/user-attachments/assets/2d862268-7f53-4c85-861c-83c890d55749)

**Comment by catalin7** [comment]
> Thanks for sharing I worked also on it and I was able to create my own one from classic lcd (no oled) by removing some back parts (not that easy, I broke some 😅)
> 
> The most difficult part is to find an homogenized light source..
> 
> ![Image](https://github.com/user-attachments/assets/2b6d6cdf-26cf-4585-95c8-282ed0973e23) ![Image](https://github.com/user-attachments/assets/c4394882-78a0-461d-9550-7d240e3eb77d) ![Image](https://github.com/user-attachments/assets/c2f2a9de-7f15-4f39-8826-6325df35f4a7)

nice job, tho if you dont magnify it too much you wont have that light problem. The led that im using is probably drawing some 10 ma. The clcoks on the ceiling are about 10-15cm, the big one is aboyut maybe 20cm

**Comment by catalin7** [comment]
or make smaller characters on a black background lcd  screen, otherwise its too much light on the  ceiling . Mines are only for the night , no daylight

**Comment by catalin7** [comment]
this is one of my projects, it uses a projector from a clock ceiling

**Comment by catalin7** [comment]
![Image](https://github.com/user-attachments/assets/9083278c-eaa5-4608-8a9b-3785d0515eee)
![Image](https://github.com/user-attachments/assets/91d65566-9baf-4352-a95e-3930d53152f6)
![Image](https://github.com/user-attachments/assets/71e0baac-e841-43c8-8846-c65841f0054a)
![Image](https://github.com/user-attachments/assets/7b75f773-d578-41c3-a1b3-d35fdfa13354)
![Image](https://github.com/user-attachments/assets/ba50ab4e-216f-4982-9636-ad42009bae18)
![Image](https://github.com/user-attachments/assets/5bc2f83e-5421-4ec8-a48c-a495930a91a2)
