### ISSUE TITLE
Transfer STM32 program

### ISSUE THREAD

**Issue by AmbroAnalog** [shufps/diy-projector-clock#5]
First of all many thanks for your great project! 
I have assembled the boards so far. 

Now I am at the point where I want to transfer your software via my ST-Link V2 to the STM32.

Which files from the _src_ folder do I need and which program would you recommend?

**Comment by shufps** [comment]
Hi, you could try it with openocd like
```
openocd -f myboard.cfg -c "program ./Release/beamer1.bin exit 0x08000000"
```

I added the binary file to the repository. The `myboard.cfg` is in the src-directory, the binary is in `src/Release`.

If this doesn't work, you could use other tools like `st-flash` (I think if I remember correctly). There should be plenty of tools to write a .hex or .bin to a stm32f103 with a STLinkV2.

Good luck :)
